networks:
  mgmt:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-9
    ipam:
      config:
      - subnet: 10.254.254.0/24
  xrd01-gi1-xrd02-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-0
    internal: true
    name: xrd01-gi1-xrd02-gi0
  xrd01-gi2-xrd05-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-1
    internal: true
    name: xrd01-gi2-xrd05-gi0
  xrd01-gi3:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-14
    internal: true
    name: xrd01-gi3
  xrd01-host:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-10
    ipam:
      config:
      - subnet: 10.101.1.0/24
  xrd02-gi1-xrd03-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-2
    internal: true
    name: xrd02-gi1-xrd03-gi0
  xrd02-gi2-xrd06-gi1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-3
    internal: true
    name: xrd02-gi2-xrd06-gi1
  xrd02-gi3:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-15
    internal: true
    name: xrd02-gi3
  xrd03-gi1-xrd04-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-4
    internal: true
    name: xrd03-gi1-xrd04-gi0
  xrd03-gi2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-16
    internal: true
    name: xrd03-gi2
  xrd03-gi3:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-17
    internal: true
    name: xrd03-gi3
  xrd04-gi1-xrd07-gi1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-5
    internal: true
    name: xrd04-gi1-xrd07-gi1
  xrd04-gi2-xrd05-gi1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-6
    internal: true
    name: xrd04-gi2-xrd05-gi1
  xrd04-gi3:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-18
    internal: true
    name: xrd04-gi3
  xrd05-gi2-xrd06-gi2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-7
    internal: true
    name: xrd05-gi2-xrd06-gi2
  xrd05-host:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-11
    ipam:
      config:
      - subnet: 10.1.1.24/29
  xrd06-gi0-xrd07-gi2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-8
    internal: true
    name: xrd06-gi0-xrd07-gi2
  xrd06-host:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-12
    ipam:
      config:
      - subnet: 10.1.1.32/29
  xrd07-gi3:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-19
    internal: true
    name: xrd07-gi3
  xrd07-host:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-13
    ipam:
      config:
      - subnet: 10.107.1.0/24
services:
  source:
    cap_add:
    - NET_ADMIN
    command: /bin/sh -c "ip route add 10.0.0.0/8 via 10.0.95.1 && /bin/sh"
    container_name: source
    image: alpine:3.15
    networks:
      xrd01-host:
        ipv4_address: 10.101.1.99
    stdin_open: true
    tty: true
  xrd01:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    - SYS_RAWIO
    cap_drop:
    - all
    container_name: xrd01
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-100,xr_name=Gi0/0/0/0,chksum;linux:xr-00,xr_name=Gi0/0/0/1;linux:xr-10,xr_name=Gi0/0/0/2;linux:xr-140,xr_name=Gi0/0/0/3
      XR_MGMT_INTERFACES: linux:xr-90,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd01-gi1-xrd02-gi0: null
      xrd01-gi2-xrd05-gi0: null
      xrd01-gi3: null
      xrd01-host: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./config/xrd01.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd01:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd02:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    - SYS_RAWIO
    cap_drop:
    - all
    container_name: xrd02
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-00,xr_name=Gi0/0/0/0;linux:xr-20,xr_name=Gi0/0/0/1;linux:xr-30,xr_name=Gi0/0/0/2;linux:xr-150,xr_name=Gi0/0/0/3
      XR_MGMT_INTERFACES: linux:xr-90,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd01-gi1-xrd02-gi0: null
      xrd02-gi1-xrd03-gi0: null
      xrd02-gi2-xrd06-gi1: null
      xrd02-gi3: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./config/xrd02.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd02:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd03:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    - SYS_RAWIO
    cap_drop:
    - all
    container_name: xrd03
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-20,xr_name=Gi0/0/0/0;linux:xr-40,xr_name=Gi0/0/0/1;linux:xr-160,xr_name=Gi0/0/0/2;linux:xr-170,xr_name=Gi0/0/0/3
      XR_MGMT_INTERFACES: linux:xr-90,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd02-gi1-xrd03-gi0: null
      xrd03-gi1-xrd04-gi0: null
      xrd03-gi2: null
      xrd03-gi3: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./config/xrd03.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd03:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd04:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    - SYS_RAWIO
    cap_drop:
    - all
    container_name: xrd04
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-40,xr_name=Gi0/0/0/0;linux:xr-50,xr_name=Gi0/0/0/1;linux:xr-60,xr_name=Gi0/0/0/2;linux:xr-180,xr_name=Gi0/0/0/3
      XR_MGMT_INTERFACES: linux:xr-90,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd03-gi1-xrd04-gi0: null
      xrd04-gi1-xrd07-gi1: null
      xrd04-gi2-xrd05-gi1: null
      xrd04-gi3: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./config/xrd04.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd04:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd05:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    - SYS_RAWIO
    cap_drop:
    - all
    container_name: xrd05
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-10,xr_name=Gi0/0/0/0;linux:xr-60,xr_name=Gi0/0/0/1;linux:xr-70,xr_name=Gi0/0/0/2;linux:xr-110,xr_name=Gi0/0/0/3,chksum
      XR_MGMT_INTERFACES: linux:xr-90,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd01-gi2-xrd05-gi0: null
      xrd04-gi2-xrd05-gi1: null
      xrd05-gi2-xrd06-gi2: null
      xrd05-host: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./config/xrd05.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd05:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd06:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    - SYS_RAWIO
    cap_drop:
    - all
    container_name: xrd06
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-80,xr_name=Gi0/0/0/0;linux:xr-30,xr_name=Gi0/0/0/1;linux:xr-70,xr_name=Gi0/0/0/2;linux:xr-120,xr_name=Gi0/0/0/3,chksum
      XR_MGMT_INTERFACES: linux:xr-90,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd02-gi2-xrd06-gi1: null
      xrd05-gi2-xrd06-gi2: null
      xrd06-gi0-xrd07-gi2: null
      xrd06-host: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./config/xrd06.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd06:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd07:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    - SYS_RAWIO
    cap_drop:
    - all
    container_name: xrd07
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-130,xr_name=Gi0/0/0/0,chksum;linux:xr-50,xr_name=Gi0/0/0/1;linux:xr-80,xr_name=Gi0/0/0/2;linux:xr-190,xr_name=Gi0/0/0/3
      XR_MGMT_INTERFACES: linux:xr-90,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd04-gi1-xrd07-gi1: null
      xrd06-gi0-xrd07-gi2: null
      xrd07-gi3: null
      xrd07-host: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./config/xrd07.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd07:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
version: '2.4'
volumes:
  xrd01:
    name: xrd01
  xrd02:
    name: xrd02
  xrd03:
    name: xrd03
  xrd04:
    name: xrd04
  xrd05:
    name: xrd05
  xrd06:
    name: xrd06
  xrd07:
    name: xrd07
